#!/usr/bin/env bash
# init script control over the daemon variables $0 $1 are like argv
. /lib/lsb/init-functions
start() {
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop() {
    sudo kill -15 "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
}
restart() {
    sudo kill -15 "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
}
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
